networks:
  default:
    driver: bridge
    name: roboshop
    external: true

services:
  mongodb:
    image: jay1303/mongodb:v1
    container_name: mongodb

  catalogue:
    image: jay1303/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb

  redis:
    image: redis:7.0
    container_name: redis

  user:
    image: jay1303/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis

  cart:
    image: jay1303/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue

  mysql:
    image: jay1303/mysql:v1
    container_name: mysql
  
  shipping:
    image: jay1303/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123

  payment:
    image: jay1303/payment:v1
    container_name: payment
    depends_on:
      - cart
      - user
      - rabbitmq

  frontend:
    image: jay1303/frontend:v1
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
    